apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-oncoscapev2-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oncoscapev2-test
    spec:
      containers:
      - name: oncoscapev2-test
        image: fredhutch/oncoscape:test
        ports:
        - name: v2-test-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: v2-test
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: v2-test-port
    protocol: TCP
    name: http
  selector:
    app: oncoscapev2-test
    