apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-notitia-python
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notitia-python
    spec:
      containers:
      - name: notitia-python
        image: canaantt/notitia-python:latest
        ports:
        - name: python-port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python
  labels:
    app: notitia-python
    prometheus-enabled: "true"
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30303
    targetPort: python-port
    protocol: TCP
    name: http
  selector:
    app: notitia-python
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notitia-python
  labels:
    team: backend-service
    prometheus-enabled: "true"
spec:
  selector:
    matchLabels:
      app: notitia-python
  endpoints:
  - port: python-port

    