apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ocpu-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: deployment-notitia-ocpu
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
